version: 1

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: format_1
        #args: (sys.stdout,)

formatters:
    format_1: 
        format: "[%(asctime)s][%(levelname)s][%(filename)s:%(lineno)d] %(message)s"

root:
    level: NOTSET
    handlers: [console]
    propogate: yes