scrape_configs:
  - job_name: "sonic-exporter"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["10.10.131.111:9101","10.10.130.9:9101","10.10.130.10:9101","10.10.130.11:9101",] #Switch IP must be updated here
  - job_name: "node-exporter"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["10.10.131.111:9100","10.10.130.9:9100","10.10.130.10:9100","10.10.130.11:9100"] #Switch IP must be updated here

